package com.group_0471.flybook;

import backend.BackendControlPanel;
import backend.exceptions.NoPermissionException;
import backend.exceptions.NoSuchEntryException;
import backend.managers.ClientInfo;
import android.app.ActionBar.LayoutParams;
import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.ActionBarActivity;
import android.support.v4.app.NavUtils;
import android.util.Log;
import android.view.MenuItem;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.RelativeLayout;

/**
 * An activity representing a single ClientInfo detail screen. This activity is
 * only used on handset devices. On tablet-size devices, item details are
 * presented side-by-side with a list of items in a
 * {@link ClientInfoListActivity}.
 * <p>
 * This activity is mostly just a 'shell' activity containing nothing more than
 * a {@link ClientInfoDetailFragment}.
 */
public class ClientInfoDetailActivity extends ActionBarActivity {

	/** entire method is auto-generated by eclipse 
	 * {@inheritDoc}
	 */
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_clientinfo_detail);
		Intent i = new Intent(this, ClientInfoListActivity.class);
		
		
		// Show the Up button in the action bar.
		getSupportActionBar().setDisplayHomeAsUpEnabled(true);

		// savedInstanceState is non-null when there is fragment state
		// saved from previous configurations of this activity
		// (e.g. when rotating the screen from portrait to landscape).
		// In this case, the fragment will automatically be re-added
		// to its container so we don't need to manually add it.
		// For more information, see the Fragments API guide at:
		//
		// http://developer.android.com/guide/components/fragments.html
		//
		if (savedInstanceState == null) {
			// Create the detail fragment and add it to the activity
			// using a fragment transaction.
			Bundle arguments = new Bundle();
			arguments.putString(
					ClientInfoDetailFragment.ARG_ITEM_ID,
					getIntent().getStringExtra(
							ClientInfoDetailFragment.ARG_ITEM_ID));
			ClientInfoDetailFragment fragment = new ClientInfoDetailFragment();
			fragment.setArguments(arguments);
			getSupportFragmentManager().beginTransaction()
			.add(R.id.clientinfo_detail_container, fragment).commit();
		}
	}

	/**defines what happens when menu items in ActionBar are pressed
	 * {@inheritDoc}
	 */
	@Override
	public boolean onOptionsItemSelected(MenuItem item) {
		int id = item.getItemId();
		if (id == android.R.id.home) {
			/*generated by eclipse, navUtils goes 1 activity up (back/home button) */
			NavUtils.navigateUpTo(this, new Intent(this,
					ClientInfoListActivity.class));
			return true;
		}else if (id == R.id.logout){
			/* redirect user to main menu & log them out */
			Intent i = new Intent(this, MainActivity.class);
			BackendControlPanel.getInstance(null).logout();
			startActivity(i);
		}else if (id == R.id.account_settings){ 
			/* redirect user to account settings page */
			Intent i = new Intent(this, ClientInfoListActivity.class);
			startActivity(i);
		}
		return super.onOptionsItemSelected(item);
	}

	/**
	 * controls behavior of "SUBMIT" button in current view
	 *@param view the current view
	 */

	public void submit(View view) {
		EditText newInfoEditText = (EditText) findViewById(R.id.editText1);
		String newInfo = newInfoEditText.getText().toString();
		Log.i("submit pressed", newInfo);
		//ActivityVars.changeInfo(newInfo);
		NavUtils.navigateUpTo(this, new Intent(this,
				ClientMenu.class));
	}
	
	
}
