package com.group_0471.flybook;

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import com.group_0471.flybook.client_pinfo_values.ClientPersonalInfoValues;

/**
 * A fragment representing a single ClientInfo detail screen. This fragment is
 * either contained in a {@link ClientInfoListActivity} in two-pane mode (on
 * tablets) or a {@link ClientInfoDetailActivity} on handsets.
 */
public class ClientInfoDetailFragment extends Fragment {
	/**
	 * The fragment argument representing the item ID that this fragment
	 * represents.
	 */
	public static final String ARG_ITEM_ID = "item_id";

	/**
	 * The dummy content this fragment is presenting.
	 */
	private ClientPersonalInfoValues.DummyItem mItem;

	/**
	 * Mandatory empty constructor for the fragment manager to instantiate the
	 * fragment (e.g. upon screen orientation changes).
	 */
	public ClientInfoDetailFragment() {
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);

		if (getArguments().containsKey(ARG_ITEM_ID)) {
			// Load the dummy content specified by the fragment
			// arguments. In a real-world scenario, use a Loader
			// to load content from a content provider.
			mItem = ClientPersonalInfoValues.ITEM_MAP.get(getArguments().getString(
					ARG_ITEM_ID));
		}
	}

	/** (autogenerated method)
	 * {@inheritDoc}
	 */
	@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container,
			Bundle savedInstanceState) {
		View rootView = inflater.inflate(R.layout.fragment_clientinfo_detail,
				container, false);

		// Show the dummy content as text in a TextView.
		if (mItem != null) {
			((TextView) rootView.findViewById(R.id.clientinfo_detail))
					.setText(mItem.content);
		}

		return rootView;
	}
}
